version: 2.1

orbs:
   slack: circleci/slack@3.4.2

jobs:
  build:
    working_directory: ~/ci
    docker:
      - image: district0x/cljs-dev:85d4876
    steps:
      - checkout
      - restore_cache:
          name: Restore m2 package cache
          keys:
            - maven-cache-{{ checksum "shadow-cljs.edn" }}
            - maven-cache-
      - restore_cache:
          name: Restore npm package cache
          keys:
            - npm-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install node modules
          command: npm install
      - save_cache:
          name: Save npm package cache
          key: npm-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules/
      - run:
          name: compile contracts
          command: npx truffle compile
      - run:
          name: compile server
          command: |
            yarn deps
            yarn compile
      - save_cache:
          name: Save m2 package cache
          paths:
            - ~/.m2
          key: maven-cache-{{ checksum "shadow-cljs.edn" }}
      - slack/status:
          channel: travis-ci
          mentions: $CIRCLE_USERNAME
      - persist_to_workspace:
          root: ~/ci
          paths:
            - server/*
            - resources/public/contracts/build/*
            - node_modules/*
            - docker-builds/*
            - docker-push.sh

  deploy:
   machine: true
   steps:
     - attach_workspace:
         at: ~/ci
     - run:
         name: Deploy docker image
         command: |
           cd ~/ci
           /bin/bash docker-push.sh
     - slack/status:
         channel: travis-ci
         mentions: $CIRCLE_USERNAME

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: district0x
      - approve_deploy:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - slack/approval-notification:
          context: district0x
          message: Pending approval for deployment
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          context: district0x
          requires:
            - approve_deploy
